### ISSUE TITLE
$HOME environment variable being set to the workspace deploy directory

### ISSUE THREAD

**Issue by richardm90** [codefori/vscode-ibmi#1475]
This may have always been the case and I've only just noticed whilst recently trying out the local development functionality but when I deploy my local workspace and build my application (using gmake) I've noticed that my home directory is being set to the workspace deploy directory.

This means I can't reference my true home directory (using the $HOME environment variable) in a Makefile or a bash script that I want to execute through VS Code.

This doesn't seem right to me.

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.0.2|
|Visual Studio Code version|1.81.0|
|Operating System|linux_x64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 9.7.23
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.1
Db2 for IBM i (vscode-db2i): 0.3.3
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.12.0
Extension Authoring (extension-editing): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
GitLens — Git supercharged (gitlens): 14.2.0
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Makefile Tools (makefile-tools): 0.7.0
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TODO Highlight (vscode-todo-highlight): 1.0.5
```
</details>

<hr />

**_Not connected_** 🔌

**Comment by worksofliam** [comment]
Yep, we do the set working directory as the deploy directory - this is because most build tools expect that.

It looks like [`getDefaultVariables`](https://github.com/halcyon-tech/vscode-ibmi/blob/master/src/api/CompileTools.ts#L185) is setting `&HOME` to the working directory (which we refer to internally as `homeDirectory` even though it is not), which is then being set to `&HOME` [here](https://github.com/halcyon-tech/vscode-ibmi/blob/master/src/api/CompileTools.ts#L608).

Easy fix is to take it out of `getDefaultVariables`.

**Comment by richardm90** [comment]
Hi @worksofliam , let me give that a try.
