### ISSUE TITLE
Incorrect PATH variables when opening source file from search across files view

### ISSUE THREAD

**Issue by jdesmidt** [codefori/vscode-ibmi#1586]
When opening a file from "search across files" the PATH variables (ex. &FULLPATH) are linked to the local path and not to the deploy path on the server.

Sources are locally on my machine.
Through actions I deploy and compile them on the server.

actions.json

![image](https://github.com/codefori/vscode-ibmi/assets/115228581/b818982e-1632-4aba-9706-b40a162b0597)

Performing the action on source WRKC100R.sqlrpgle should result in :

CRTSQLRPGI OBJ(VRBPGM/WRKC100R) SRCSTMF(<strong>'/vrb/src/qilesrc/WRKC100R.sqlrpgle'</strong>) OPTION(*EVENTF) DBGVIEW(*SOURCE) CLOSQLCSR(*ENDMOD) RPGPPOPT(*LVL2) CVTCCSID(*JOB) COMPILEOPT('TGTCCSID(*JOB) PPMINOUTLN(512)')

Opening the source from the results of "search across files"

![image](https://github.com/codefori/vscode-ibmi/assets/115228581/ef175915-c9bd-495b-bc91-0339cf0884a0)

Performing the action to "deploy & compile" results in :

![image](https://github.com/codefori/vscode-ibmi/assets/115228581/a595da93-892a-4e13-be5e-b5cd999b204f)

Closing and the source and opening from "explorer" view does not solve the problem.

After renaming the source file (the file name itself, not only the extension) the path is correct again when performing the action.

![image](https://github.com/codefori/vscode-ibmi/assets/115228581/813b40cb-7237-4106-a621-1c4ff7a4d816)

**Comment by worksofliam** [comment]
Hi @jdesmidt 

Thanks for the detailed report. I am going to pick this up on Monday.

**Comment by worksofliam** [comment]
Initial reaction is something to do with the URI that is used when the tab is open.

**Comment by worksofliam** [comment]
Okay. I have looked into this and no matter where I open the file from (either Explorer or search results) I get the correct `&FULLPATH`. I am on a Mac.

@sebjulliand you're a Windows person right? Any chance you can confirm my findings here?

**Comment by sebjulliand** [comment]
@worksofliam sure thing. i've got something actually.
At first I couldn't reproduce the issue but then I added another folder in the workspace, just to see. And finally, &FULLPATH was eventually screwed. Here is why:
![image](https://github.com/codefori/vscode-ibmi/assets/11096890/c1a611c8-e1f8-4a04-8ab5-b9875b45c6e5)

So, because the driver letter is uppercase in `baseDir` and lowercase in `uri.path` which results in `relativePath` that goes back with a lot of `..` and `fullPath` being wrong.

And I just tested again and reproduced it by having at least two workspace folders in the workspace.

Since I can reproduce it, I'll fix it 😉 Expect a PR today.
