### ISSUE TITLE
API change: removing `enableSQL` configuration

### ISSUE THREAD

**Issue by worksofliam** [codefori/vscode-ibmi#1808]
As of PR #1780, we are assuming that our database backend program (`QSYS/QZDFMDB2.PGM`) will always be available.

* [x] SQL runner always available even when user doesn't have a valid CCSID: https://github.com/codefori/vscode-ibmi/pull/1828
* [ ] Remove `enableSQL` property and any conditions where it matches to `false`
* [ ] Remove setting from the Connection Settings
* [ ] Update tests to remove non-SQL test cases.

**Comment by worksofliam** [comment]
Something to think about that we could improve: better messaging to the user when QCCSID is 65535 or when the user profile isn't configured properly.

**Comment by sebjulliand** [comment]
We'll need a rock-solid troubleshooting guide and an unavoidable way to point the users to it.

**Comment by edmundreinhardt** [comment]
As the architect for Merlin which depends on Code for IBM i, I want to express my concern about this.

Many of our customers are either afraid, or do not have sufficient authority to change the CCSID configuration of the IBM i that they are doing development on.   With this change we are in effect cutting all of these customers off from VS Code support for IBM i.

In my experience with RDi, it is sometimes necessary to accommodate these less than ideal architectures so that we can support customers where they are, because they cannot change.

Please reconsider.

**Comment by Wright4i** [comment]
> Many of our customers are either afraid, or do not have sufficient authority to change the CCSID configuration of the IBM i that they are doing development on. With this change we are in effect cutting all of these customers off from VS Code support for IBM i.

IMHO, this isn't cutting off customers from VS Code support for IBM i. VS Code provides the ability to install another version of the extension with a simple right-click. Making a bump to 3.0.0 makes a clear delineation that any version prior to 3.0.0 would be suitable for them until they have been able to get those changes made through the proper channels in their organization. It sounds like the plan would be to provide improved error messages and documentation to guide the users through both downgrading and what's required to run version 3.0.0+

Properly configuring their systems is a good thing and it greatly simplifies this extension.

Perhaps an early pop-up message for invalid CCSID users is in order in the next minor version release? This `nag` message gives the users even more time to make the change so they're ready for the 3.0.0 release which is months away.

**Comment by jkyeung** [comment]
This is a worthwhile and important discussion, so I'm very glad it's happening, and glad to have Edmund's voice.

I suspect there are _many_ shops that leave their QCCSID at 65535. And either they're unaware that they should change it, or they're afraid of changing it, because everything is already working fine. Why mess with a _system value_ if things are working?

And I suspect things are working fine largely because the user profiles are set to a sensible CCSID, which already satisfies the proposed requirement.

I bet it would actually not be that hard to get shops to set the proper CCSID _somewhere_, if they haven't already. A little encouragement from IBM would go a long way at those shops. Ask them to just switch one user profile over to a real CCSID, and try it out. When they're satisfied that they haven't broken anything, they ought to be willing to switch more user profiles over. (Truly paranoid shops might still be persuaded to at least create new CCSID-assigned user profiles specifically for use with VS Code or Merlin. Certain users might then have a "VS Code" profile as well as a "green screen" profile. In any case, they would not be cut off from support, or even from the latest versions of these products.)

Better yet, if they have a dev or test partition, ask them to try changing QCCSID there. More than likely, they won't even notice anything different. (Best of all would be IBM shipping OS updates and new boxes with QCCSID already set properly, instead of leaving this particular footgun loaded when it arrives at the customer's door.)

**Comment by sebjulliand** [comment]
I do get your concern @edmundreinhardt , but I don't think it is a good idea to keep nurturing these bad practices. Stating customers can't change, looking away and saying "that's fine, carry on, we'll accommodate you" will probably not encourage people to modernize their system, on the contrary. And that would be a shame, since the M in Merlin stands for Modernization, right? 😉
On top of that, not taking advantage of all the SQL services that have been blooming lately would be a real shame since it's so powerful and convenient.

This being said, this change will not cut off customers from the extension. We may have found a way to make our SQL call use the job's default CCSID, which I think should prevent conversion issues (save for DBCS conversion, but those can be tackled in the query itself I think).

So, let's promote modern practices!

**Comment by worksofliam** [comment]
Update on this front:

We will be able to run SQL statements with no issues, even when QCCSID is 65535 and the user has no configured CCSID. We can set the CCSID of the SQL job to execute directory, and we have a way of getting the default CCSID out of the job so we can apply it correctly.

That work was done in this PR and will be released in 2.7.0: https://github.com/codefori/vscode-ibmi/pull/1828
