### ISSUE TITLE
All Configured authentication methods failed

### ISSUE THREAD

**Issue by sureshramakrishnan** [codefori/vscode-ibmi#1838]
👉🏻 Issue text goes here.

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.6.5|
|Visual Studio Code version|1.86.0|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 10.1.23
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Db2 Connect (db2connect): 2.3.1
Db2 for IBM i (vscode-db2i): 0.6.1
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.16.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

**_Not connected_** 🔌

**Comment by sureshramakrishnan** [comment]
Unable to connect to IBMi from Code for IBMi all I get is "All configured authentication methods failed" not seeing any further message. How can i solve this?

**Comment by sebjulliand** [comment]
Hi @sureshramakrishnan ,
this means that the credentials you provided were invalid. Either the user name and/or password are wrong (that happens quite often with copy/paste) or the private key you're using is not known on the remote system. Sometimes, it's because the user profile is `*DISABLED`.
Check your credentials and in doubt, use a third party tool to try to connect through SSH, like Putty since you're on Windows.
Hope this helps!
