### ISSUE TITLE
V2.12.0 update does connect  but db2forI does not work

### ISSUE THREAD

**Issue by dev-wouter** [codefori/vscode-ibmi#2181]
Hi, 

From yesterday i have issues with some VS code plugins that use the codeForIBMi plugin to connect. 
i'm able to look at all the different components in the extention but it does give an uncaught error
' NOT AUTHORIZED TO COMMAND WRKPTFGRP. (42501)'

the other plugin i'm using is arcad elias and db2forI. 
arcad elias is not able to get any component listing or show a IbmI. 
in db2forI i'm not able to execute a SQL

i did a roll back to Version 2.11.0 and everything works fine again.
updated back to v2.12.0 and had the same result so downgrades again to 2.11.0 so i can work.

in DB2forI i get this error when executing a sql with V2.12.0
'Database server component is required. Please see documentation for details.'
and in the output (db2 for I server components) i have this message 
`{"assetPath":"c:\\Users\\wovaneer\\.vscode\\extensions\\halcyontechltd.vscode-db2i-1.0.0\\dist\\codeforiserver-1.4.9.jar","assetExists":true}
{"basename":"codeforiserver-1.4.9.jar"}
{"code":0,"signal":null,"stdout":"/home/WOVANEER/.vscode/","stderr":""}
{"remotePath":"/home/WOVANEER/.vscode/codeforiserver-1.4.9.jar","ExecutablePathDir":"$HOME/.vscode/"}
{"code":3,"transferred":[]}`

if needed i can try to provide more info. 

gr wouter

**Comment by sebjulliand** [comment]
Hi @dev-wouter ,
this issue may be due to a change made to how functions get executed once Code for i is connected.

I made a build that should fix your problem. You'll still see the `NOT AUTHORIZED TO COMMAND WRKPTFGRP` (this should be delat with in the db2 for i extension itself) but it won't prevent other functions (like the one Elias depends on) from being executed.

Please install this build and let me know how it goes.
[code-for-ibmi-2.12.1-dev.0.vsix.zip](https://github.com/user-attachments/files/16311689/code-for-ibmi-2.12.1-dev.0.vsix.zip)

Thanks!

**Comment by dev-wouter** [comment]
it seems to be working. but i got this error message when connecting to elias
![image](https://github.com/user-attachments/assets/5ac9b39e-268b-4f8f-ac6d-a58fc8502342)

**Comment by sebjulliand** [comment]
Maybe try connecting from the Connection Browser then give it some time before the applications get loaded.

**Comment by dev-wouter** [comment]
oddly enough now that i have closed down VS code, and restarted it does not give that message anymore. 

thanks for the quick fix

**Comment by worksofliam** [comment]
I also just release vscode-db2i 1.1.0 which has a temp fix for this.
