### ISSUE TITLE
Supress Zeros when ctdata Arrays

### ISSUE THREAD

**Issue by hn000246** [codefori/vscode-ibmi#2244]
If i use Seu to Edit a source that include ctdata arrays is working good, but when i use code for i, it supress the zeros and update the Source. (Not correct.)
I don't know how to solvente this issue.

I'm sending you the ctdata array using Seu and the issue when i use the code for i.

Best Regards,
![image](https://github.com/user-attachments/assets/ae77909f-c0c7-48df-8bc0-6cc5dcd5110d)

![image](https://github.com/user-attachments/assets/359f0c9c-bb55-4c4f-809a-6db03b286b83)

Best Regards,

**Comment by worksofliam** [comment]
Will look into a fix tomorrow. It shouldn't be too hard.

**Comment by NextPage66** [comment]
I updated to the newest extension.
It is no longer removing the leading zeros.
It is replacing them with exponential notation.

Original Example:
![image](https://github.com/user-attachments/assets/7dd01d3d-eed7-43bb-8079-70903888a683)

VSCODE conversion:
![image](https://github.com/user-attachments/assets/ac45b4c3-8ffe-4dad-8339-d331902577ec)

**Comment by worksofliam** [comment]
@NextPage66 Are you using the version from the branch or the standard release? We haven't released the fix yet.

**Comment by NextPage66** [comment]
standard release.  Sorry i thought i saw it was released.

**Comment by NextPage66** [comment]
Any update on this issue?

**Comment by hn000246** [comment]
Do you know when will be 2.13.1 versión ready?

**Comment by chrjorgensen** [comment]
@hn000246 Version 2.13.1 was made available 3 weeks ago - as an pre-release version!

![billede](https://github.com/user-attachments/assets/aad910a7-4866-4299-8afb-ad772fd7cd30)

Two more prereleases have been created since then.
You install a prerelease version by going to the Extensions view (Ctrl-Shift-X), click on the cog for the Code for IBM i extension and select `Switch to Pre-release Version`:

![billede](https://github.com/user-attachments/assets/2688d95c-a7b8-4d3c-b6ab-47f48494eb48)

You can choose which version you want to install by going to the Extensions view (Ctrl-Shift-X), click on the cog for the Code for IBM i extension and select `Install Specific Version...` - this will give you the screen shown above (including the pre-release version if your current version is a pre-release version, otherwise only regular versions are shown).

**Comment by worksofliam** [comment]
This fix branch has not yet been merged.
