### ISSUE TITLE
SQL Statment 

### ISSUE THREAD

**Issue by sboisier** [codefori/vscode-ibmi#2278]
Hi,

Trying simple request on my IBM i System with VSCode and Code for IBM i Extension.

Table creation. This statment is working both on my iSeries SQl and on VSCode :

CREATE TABLE QTEMP.Test (
    CLE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    Valeur CHAR(10)
);

Records insertions. This statment is working both on my iSeries SQl and on VSCode :

INSERT INTO
    QTEMP.Test (Valeur)
VALUES
    ('A'),
    ('B'),
    ('C'),
    ('D'),
    ('E'),
    ('F');
   
Select statment. I This statment is working on my iSeries SQL and not on VSCode (error [SQL0104] Elément syntaxique n'est pas correct. Eléments possibles : ( + - ? : DAY INF LAG NAN RID ROW., 42601, -104) :

SELECT
    CLE,
    CASE
        WHEN CLE = 1 THEN 'FIRST' Else VALEUR End As VALEUR
FROM
    QTEMP.Test;
    
    Maybe I'm niot using the right SAQL Driver in VSCode but I don't know how to check this and how to fix my problem.
    
  Thx for helping me on this guys

**Comment by sebjulliand** [comment]
Hi @sboisier ,
I ran a query of mine with a `case when` statement and I can confirm it crashed for me too.

However, since this issue is not relalted to `Code for IBM i` but to the `vscode-db2i` extension, would you mind [opening your issue over there](https://github.com/codefori/vscode-db2i/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=)?

Thanks!

**Comment by sebjulliand** [comment]
@sboisier this is a known bug and it will be fixed soon. Going back to version `1.4.2` may avoid this problem in the meantime.
