### ISSUE TITLE
Cannot regenerate service certificate - Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by JBuck51** [codefori/vscode-ibmi#2279]
Server status
![image](https://github.com/user-attachments/assets/51c940b9-7de3-4872-97d3-6da6fa53331b)

**Describe the bug**
Cannot start the debug service. I receive the error message below
![image](https://github.com/user-attachments/assets/7c073508-d542-4ad9-bc66-b063f7c12878)

**To Reproduce**
1. Deleted certificates from /QIBM/UserData/IBMiDebugService/certs
2. Clicked on connection > Settings > Debugger
3. ![image](https://github.com/user-attachments/assets/ca4d640a-627b-4558-b4b1-6107f638bee5)

**Expected behavior**
1. Expected the service certificates to be regenerated and downloaded windows client
2. To be able to start the debug service

**Environment (please complete the following information):**
 - Extension version **IBM I Debug v2.0.1**
 - IBM i OS version **7.5 - required PTF's installed**

**Comment by sebjulliand** [comment]
Hi @JBuck51 ,
could you copy/paste the whole `Code for IBM i` output right after the error shows up?
![code for i output](https://github.com/codefori/vscode-ibmi/assets/11096890/88bc7363-2402-419f-b173-309358b914b9)

This seems to be a DNS or networking issue. The process generating the certificate will run the `hostname` command through the remote shell to get the LPAR hostname as defined in the TCP configuration. Then it will run a local DNS lookup to resolve the IP of this hostname. According to the error message, if you try to ping the `Impower.impowertechnologies.com` address from your computer, it's expected to fail. Is it the case and is `Impower.impowertechnologies.com` the actual and expected hostname for the LPAR you're trying to work with?

**Comment by JBuck51** [comment]
From what I can see the configuration is as expected.

Impower.impowertechnologies.com resolves locally on the partition to the correct IP interface.


  *   L


[Service Express]<https://www.serviceexpress.com/>

Larry Bolhuis
IBM i Infrastructure Advisor

Mobile: 1.616.240.4509
for service: 1.800.940.5585
serviceexpress.com<http://www.serviceexpress.com/>

people-powered data center solutions

IBM Champion for Power
IBM Certified Systems Expert - Virtualization Technical Support for IBM i -v1
COMMON Certified Business Computing Professional

**Comment by sebjulliand** [comment]
Hi Jim,
sorry I can't see the screenshots; they don't make it when replying by e-mail.

So on Larry's side, everything seems to be in order.
What about from the PC tried to generate the certificate from? Does performing a `ping Impower.impowertechnologies.com` from a Windows CMD terminal (or a shell if you're on Mac or Linux) work? If not, that may explain the issue (i. e. DNS lookup issue). If it does work on your side, I, uh...will need do dig a bit more 😅

On the other hand, you can also ask Larry to generate and start the Debug Service on this LPAR, using VS Code (just once; once it's configured and started, it can be used by anyone).

**Comment by JBuck51** [comment]
Hi Sebastien,
I've included a screenshot of the ping from my PC. My connection is the green arrow and the debugger comes back saying it cannot connect to the other url.
![image](https://github.com/user-attachments/assets/a7e0fa6d-256a-4873-a07b-5eaf349c5b65)

I logged into the VPN and I was able to start the Debug Server and debug a program. A Victory! :)

I disconnected from the VPN and connected using the external URL and tried batch debugging the same program. I received the error message below.
![image](https://github.com/user-attachments/assets/06b4a241-f34a-4b7b-abe1-bd86b9d1fce6)


I tried running the debugger on another computer (same program and servers running) and received a different message
![DebugError](https://github.com/user-attachments/assets/b6f45b90-5df2-4cd9-be3a-ef87aec31f01)

**Comment by sebjulliand** [comment]
Thanks for digging into this Jim. It all makes sense now! Even though that won't solve your issue, I'm afraid.

I'll try to sum it up: the Debug Service is basically a REST API web server that runs on HTTPS. HTTPS requires a certificate - certificate that can be generated by Code for IBM i (or imported; I'll come back to that later). That certificate is generated for a given IP address, short hostname (e.g. `Impwer`) and qualified hostname (`Impwer.ibmpowertechnologies.com`).

When the debug client connects from VS Code, it checks that:
- the local certificate matches the remote certificate
- the ip/name used to connect to the service matches the certificate IP/hostnames. If it doesn't, you get this:
![image](https://github.com/user-attachments/assets/2a1084a2-ac1d-4d3f-86db-7cf51d91c944)

In your case, the public IP/Hostname of your LPAR is different from its private IP/Hostname. Without using your VPN connection, you connected with the public address. That explains the first issue: the certificate generation process gets the hostname remotely by running the `hostname` command on the LPAR, and then looks up the IP address using a dns lookup from the client side. Since the private hostname cannot be resolved wihtout the VPN connection, you had this issue:
![image](https://github.com/user-attachments/assets/feb00af7-bd5e-4bf0-8e53-8a22a8f33aab)

Connecting through the VPN allowed you to:
- Connect using the private hostname
- Generate the certificate and start the service
- Connect to the service with the hostname matching the certificate's
Everything was consistent across the board, hence a Victory ✌🏻

Then of course, disconnecting the VPN and trying to connect using the public address gave you the "address mismatch" error.

...Phew!...

I mentioned earlier the fact that the service certificate can also be imported. This may be a good way to install a certificate that could work for both the private and public hostname, by specifying every possible address/hostnames when generating the certificate manually. Once generated, it can be imported and installed by Code for i.

I guess if you run these commands on your LPAR, through a shell, would generate a valid certificate for both addresses:
```
/QOpenSys/usr/bin/openssl genrsa -out debug_service.key 2048
/QOpenSys/usr/bin/openssl req -new -key debug_service.key -out debug_service.csr -subj '/CN=Impwer.ibmpowertechnologies.com'`,
/QOpenSys/usr/bin/openssl x509 -req -in debug_service.csr -signkey debug_service.key -out debug_service.crt -days 1095 -sha256 -req -extfile <(printf "DNS:Impwer.ibmpowertechnologies.com,IP:172.20.26.10,subjectAltName=Impwer,subjectAltName=ibmi.ibmpowertechnologies.com")
/QOpenSys/usr/bin/openssl pkcs12 -export -out debug_service.pfx -inkey debug_service.key -in debug_service.crt -password pass:MyPasswordIsNotVeryGoodButLong,
```

Once generated, download it from the IFS. Then click on the "Generate service certificate" action from the IBM Debugger view (right click on the Debug Service).
![image](https://github.com/user-attachments/assets/da93fbdd-c99d-4acc-ba13-a7c7dd16fd99)

The dialog being displayed will offer to generate or import a certificate.
![image](https://github.com/user-attachments/assets/e8df9aa4-773c-4e62-9ca0-ab9186cb8082)

Select the certificate you just downloaded (its password will be `MyPasswordIsNotVeryGoodButLong`). And then...it should work!

That's all I can think of for now 😅

**Comment by JBuck51** [comment]
Hi Sebastien,
Thanks for the explanation, it helps me to understand what is going on! I forwarded your email to Larry and he changed the system name to IBMI instead of IMPOWER and that seems to have fixed the problem. Thanks for your efforts! :)
Jim

**Comment by sebjulliand** [comment]
My pleasure Jim, glad it's sorted out! 😃
