### ISSUE TITLE
SEP debug ignoring source set breakpoints

### ISSUE THREAD

**Issue by begwhite** [codefori/vscode-ibmi#2308]
Type: <b>Bug</b>

SEP debug ignoring source set activated breakpoints and not allowing to set new breakpoints in the "Listing" tab. Either this is a bug or I'm missing some setting to get SEP debug to stop at activated defined breakpoints and/or not allowing new breakpoints in the "Listing" tab when running a program with a SEP defined .

Extension version: 2.13.5
VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.69GB (14.24GB free)|
|Process Argv|--crash-reporter-id 7563cf75-277c-468d-b1a1-280e8b7281c6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca1:31156133
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31164048
icondisabled:31158250

```

</details>

**Comment by mkwan01** [comment]
The description is not very clear. If you are talking about the issue that we cannot set line breakpoints in a *LIST source, then this issue is not SEP specific. It also applies to batch debug. The real cause for the problem is that the LISTING editor does not support source breakpoint by default. Please check the following setting to allow source breakpoint in LISTING editor:
**Allow setting breakpoints in any file** under **Debug > Allow Breakpoints Everywhere**

![image](https://github.com/user-attachments/assets/2f879b9f-9371-4a2a-ac4f-33f0c95921c8)

We can set source breakpoints in LISTING source after checking the above setting:
![image](https://github.com/user-attachments/assets/154726c1-f38e-4833-bb82-27533617d821)
